# Use the official Consul Exporter image
FROM prom/consul-exporter:latest

# Set environment variables from .env file for the consul connection
# The .env file should be used with `docker run --env-file`
# Example: CONSUL_SERVER=hostname:8500

# Expose the default Consul Exporter port
EXPOSE 9107
