---
node_exporter_version: "1.9.1"
node_exporter_user: node_exporter
node_exporter_group: node_exporter
node_exporter_bin_dir: /usr/local/bin
node_exporter_service_file: /etc/systemd/system/node_exporter.service
