# Use the official Grafana image
FROM grafana/grafana:latest

# Set environment variables from .env file
# The .env file should be used with `docker run --env-file`
# Example: GF_SECURITY_ADMIN_PASSWORD=admin

# Expose the default Grafana port
EXPOSE 3000
