# Use the official Memcached Exporter image
FROM prom/memcached-exporter:latest

# Set environment variables from .env file for the memcached connection
# The .env file should be used with `docker run --env-file`
# Example: MEMCACHED_ADDR=hostname:11211

# Expose the default Memcached Exporter port
EXPOSE 9150
