# Use the official MongoDB Exporter image
FROM percona/mongodb_exporter:latest

# Set environment variables from .env file for the mongodb connection
# The .env file should be used with `docker run --env-file`
# Example: MONGODB_URI=mongodb://hostname:27017

# Expose the default MongoDB Exporter port
EXPOSE 9216
