---

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present
    update_cache: yes

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Import Grafana GPG key
  ansible.builtin.shell:
    cmd: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg
  args:
    creates: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: Create Grafana config directory
  ansible.builtin.file:
    path: /etc/grafana
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0755'

- name: Template Grafana config file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_file }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0644'
  notify: restart grafana

- name: Create Grafana provisioning directory
  ansible.builtin.file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0755'

- name: Template Grafana datasources file
  ansible.builtin.template:
    src: datasources.yml.j2
    dest: /etc/grafana/provisioning/datasources/datasources.yml
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0644'
  notify: restart grafana

- name: Start and enable Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes
