# Use the official Redis Exporter image
FROM oliver006/redis_exporter:latest

# Set environment variables from .env file for the redis connection
# The .env file should be used with `docker run --env-file`
# Example: REDIS_ADDR=redis://hostname:6379

# Expose the default Redis Exporter port
EXPOSE 9121
