# Use the official Loki image
FROM grafana/loki:latest

# Add a loki configuration file
# This file should be mounted as a volume
# ADD loki-config.yaml /etc/loki/

# Expose the default Loki port
EXPOSE 3100
