---
- name: Include default variables
  ansible.builtin.include_vars:
    file: defaults/main.yml

- name: Create a group for Prometheus
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create a user for Prometheus
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    system: yes
    shell: /bin/false
    create_home: no

- name: Create Prometheus config directory
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Download and unarchive Prometheus
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"

- name: Copy prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/"
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
  loop:
    - prometheus
    - promtool

- name: Copy prometheus console libraries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_config_dir }}/"
    remote_src: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  loop:
    - console_libraries
    - consoles

- name: Template prometheus config file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  notify: restart prometheus

- name: Template prometheus systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: "{{ prometheus_service_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus

- name: Ensure prometheus service is started and enabled
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Cleanup prometheus archive and directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"
    - "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

