# Use the official Prometheus image
FROM prom/prometheus:latest

# Add a prometheus configuration file
# This file should be mounted as a volume
# ADD prometheus.yml /etc/prometheus/

# Expose the default Prometheus port
EXPOSE 9090
