# Use the official MySQLd Exporter image
FROM prom/mysqld-exporter:latest

# Set environment variables from .env file for the database connection
# The .env file should be used with `docker run --env-file`
# Example: DATA_SOURCE_NAME=user:password@(hostname:3306)/

# Expose the default MySQLd Exporter port
EXPOSE 9104
