# Use the official Blackbox Exporter image
FROM prom/blackbox-exporter:latest

# Add a blackbox configuration file
# This file should be mounted as a volume
# ADD blackbox.yml /etc/blackbox_exporter/

# Expose the default Blackbox Exporter port
EXPOSE 9115
