# Use the official SNMP Exporter image
FROM prom/snmp-exporter:latest

# Add a snmp configuration file
# This file should be mounted as a volume
# ADD snmp.yml /etc/snmp_exporter/

# Expose the default SNMP Exporter port
EXPOSE 9116
