# Use the official Elasticsearch Exporter image
FROM prometheuscommunity/elasticsearch-exporter:latest

# Set environment variables from .env file for the elasticsearch connection
# The .env file should be used with `docker run --env-file`
# Example: ES_URI=http://hostname:9200

# Expose the default Elasticsearch Exporter port
EXPOSE 9114
