# Use the official Postgres Exporter image
FROM quay.io/prometheuscommunity/postgres-exporter:latest

# Set environment variables from .env file for the database connection
# The .env file should be used with `docker run --env-file`
# Example: DATA_SOURCE_NAME=postgresql://user:password@hostname:5432/postgres?sslmode=disable

# Expose the default Postgres Exporter port
EXPOSE 9187
